In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
import rpy2

In [2]:
import rpy2.robjects as ro
import rpy2.robjects.numpy2ri

In [3]:
rpy2.robjects.numpy2ri.activate()

In [4]:
codigo_r = """
saludar <- function(cadena){
    return(paste("Hola, ", cadena))
}
"""

In [5]:
ro.r(codigo_r)

<rpy2.robjects.functions.SignatureTranslatedFunction object at 0x11bb44948> [RTYPES.CLOSXP]
R classes: ('function',)

In [6]:
saludar_py = ro.globalenv["saludar"]

In [7]:
saludar_py("Pablo T")

<rpy2.robjects.vectors.StrVector object at 0x11a1e9988> [RTYPES.STRSXP]
R classes: ('character',)
['Hola,  Pablo T']

In [8]:
res=saludar_py("Pablo T")
res[0]

'Hola,  Pablo T'

In [9]:
type(res)

rpy2.robjects.vectors.StrVector

In [10]:
print(saludar_py.r_repr())

function (cadena) 
{
    return(paste("Hola, ", cadena))
}


In [11]:
var_from_python = ro.FloatVector(np.arange(1,5,.1))

In [12]:
var_from_python

<rpy2.robjects.vectors.FloatVector object at 0x11bb5bd08> [RTYPES.REALSXP]
R classes: ('numeric',)
[1.000000, 1.100000, 1.200000, 1.300000, ..., 4.600000, 4.700000, 4.800000, 4.900000]

In [13]:
print(var_from_python.r_repr())

c(1, 1.1, 1.2, 1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9, 2, 2.1, 2.2, 
2.3, 2.4, 2.5, 2.6, 2.7, 2.8, 2.9, 3, 3.1, 3.2, 3.3, 3.4, 3.5, 
3.6, 3.7, 3.8, 3.9, 4, 4.1, 4.2, 4.3, 4.4, 4.5, 4.6, 4.7, 4.8, 
4.9)


In [15]:
ro.globalenv["var_to_r"]=var_from_python

In [16]:
ro.r("var_to_r")

array([1. , 1.1, 1.2, 1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9, 2. , 2.1, 2.2,
       2.3, 2.4, 2.5, 2.6, 2.7, 2.8, 2.9, 3. , 3.1, 3.2, 3.3, 3.4, 3.5,
       3.6, 3.7, 3.8, 3.9, 4. , 4.1, 4.2, 4.3, 4.4, 4.5, 4.6, 4.7, 4.8,
       4.9])

In [17]:
ro.r("sum(var_to_r)")

array([118.])

In [18]:
ro.r("mean(var_to_r)")

array([2.95])

In [19]:
ro.r("sd(var_to_r)")

array([1.16904519])

In [20]:
np.sum(var_from_python)

118.00000000000007

In [21]:
np.mean(var_from_python)

2.950000000000002

In [22]:
ro.r("summary(var_to_r)")

array([1.   , 1.975, 2.95 , 2.95 , 3.925, 4.9  ])

In [23]:
ro.r("hist(var_to_r)")

<rpy2.robjects.vectors.ListVector object at 0x11bb6a188> [RTYPES.VECSXP]
R classes: ('histogram',)
[Float..., IntSe..., Float..., Float..., StrSe..., BoolS...]
  breaks: <class 'rpy2.rinterface.FloatSexpVector'>
  <rpy2.rinterface.FloatSexpVector object at 0x11bb6aec8> [RTYPES.REALSXP]
  counts: <class 'rpy2.rinterface.IntSexpVector'>
  <rpy2.rinterface.IntSexpVector object at 0x11bb6d0c8> [RTYPES.INTSXP]
  density: <class 'rpy2.rinterface.FloatSexpVector'>
  <rpy2.rinterface.FloatSexpVector object at 0x11be3d848> [RTYPES.REALSXP]
  mids: <class 'rpy2.rinterface.FloatSexpVector'>
  <rpy2.rinterface.FloatSexpVector object at 0x11be3dbc8> [RTYPES.REALSXP]
  xname: <class 'rpy2.rinterface_lib.sexp.StrSexpVector'>
  <rpy2.rinterface_lib.sexp.StrSexpVector object at 0x11be3de48> [RTYPES.STRSXP]
  equidist: <class 'rpy2.rinterface.BoolSexpVector'>
  <rpy2.rinterface.BoolSexpVector object at 0x11be3d788> [RTYPES.LGLSXP]

# Trabajar de forma conjunta entre R y Python

In [24]:
from rpy2.robjects.packages import importr

In [ ]:
ro.r("install.packages('extRemes')")

--- Please select a CRAN mirror for use in this session ---


In [ ]:
extremes = importr("extRemes")