# El método de k-means

In [1]:
import numpy as np

In [2]:
data = np.random.random(90).reshape(30,3)
data

array([[0.58323422, 0.01495712, 0.1111449 ],
       [0.5133426 , 0.71319954, 0.99784494],
       [0.94828858, 0.44552298, 0.01603566],
       [0.78447804, 0.47997124, 0.29880344],
       [0.03149648, 0.41292511, 0.14196079],
       [0.34719848, 0.06489865, 0.300173  ],
       [0.94177055, 0.68808833, 0.02091458],
       [0.01941938, 0.51682841, 0.93499586],
       [0.17627073, 0.98844615, 0.04234676],
       [0.46509907, 0.66860386, 0.15187332],
       [0.70092006, 0.76264768, 0.13046739],
       [0.57223008, 0.25592009, 0.91297242],
       [0.64613443, 0.87124769, 0.44934838],
       [0.56873886, 0.87300384, 0.6597172 ],
       [0.37514316, 0.10279411, 0.16004914],
       [0.54190352, 0.49020511, 0.57859078],
       [0.99765848, 0.59058127, 0.32288853],
       [0.56019652, 0.83050983, 0.47259319],
       [0.69498167, 0.37791666, 0.94163711],
       [0.97537402, 0.11607368, 0.18887343],
       [0.28136346, 0.27096044, 0.39655586],
       [0.31649287, 0.7303639 , 0.73176728],
       [0.

In [4]:
# Seleccion al azar de centroides
c1 = np.random.choice(range(len(data)))
c2 = np.random.choice(range(len(data)))
clust_centers = np.vstack([data[c1],data[c2]])
clust_centers

array([[0.99765848, 0.59058127, 0.32288853],
       [0.77088684, 0.56842395, 0.23254044]])

In [5]:
from scipy.cluster.vq import vq

In [6]:
# array1: clase a la que pertenecen del cluster
# array2: distancia a la que se encuentra del varicentro del cluster
vq(data, clust_centers)

(array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1,
        1, 0, 0, 1, 1, 1, 1, 1]),
 array([0.59688853, 0.82035357, 0.30569649, 0.11135254, 0.76097482,
        0.66153134, 0.29716378, 1.02995585, 0.75243644, 0.33173689,
        0.23029788, 0.77466822, 0.39277355, 0.562239  , 0.61536915,
        0.42225867, 0.        , 0.4131643 , 0.72089479, 0.49357279,
        0.59583448, 0.6942088 , 0.56649203, 0.55526888, 0.60561466,
        0.59336768, 0.92501284, 0.51753655, 0.        , 0.73605559]))

In [7]:
from scipy.cluster.vq import kmeans

In [8]:
# array1: 
# ubicación del varicentro 1
# ubicación del varicentro 2
# ,
# constante final Suma cuadrada normalizada
kmeans(data, clust_centers)

(array([[0.85056194, 0.41736342, 0.20895225],
        [0.39272302, 0.52793596, 0.51730853]]),
 0.4081900574297921)